name: Build & Deploy BlazorApp

on:
    push:
        branches: ["main"]
    
env: 
    DOTNET_VERSION: '8.0.x'
    NODE_VERSION: '22.x'

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            # 1. Descargar el código
            - name: Descargar el código
              uses: actions/checkout@v4

            # 2. Instalar .NET
            - name: Setup -NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: ${{ env.DOTNET_VERSION }}

            # 3. Pacquetes Nuget
            - uses: actions/cache@v3
              with:
                path: ~/.nuget/packages
                key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
            # Instalar Node
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: ${{ env.NODE_VERSION }}

            # Restore an publish
            - name: Publicar APP Blazor
              run: |
                    dotnet restore
                    # Inyectar la API KEY
                    echo "{\"OpenWeather\":{\"Key\":\"${{ secrets.OPENWEATHER_KEY }}\"}}" > skyCast/appsettings.Production.json
                    dotnet publish skyCast/skyCast.csproj -c Release -o ./publish

            # Artifact
            - name: Guardar artefacto
              uses: actions/upload-artifact@v3
              with:
                name: publish
                path: publish

            # Despliegue
            - name: Desplegar github pages
              uses: peaceiris/actions-gh-pages@v4
              with: 
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./publish/wwwroot
                force_orphan: true
